<a href="https://colab.research.google.com/github/EddyEjembi/Transformers/blob/main/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 35.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 55.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 15.9 MB/s eta 0:00:00


In [ ]:
from transformers import pipeline

In [ ]:
classifier = pipeline("sentiment-analysis")
classifier("Men i love Machine Learning")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9993935823440552}]

In [ ]:
classifier("I kinda feel sory for them cos they never knew you like i do")

[{'label': 'POSITIVE', 'score': 0.9882586002349854}]

In [ ]:
classifier("You said forever but i drive alone pass your street")

[{'label': 'NEGATIVE', 'score': 0.9785675406455994}]

In [ ]:
classifier2 = pipeline("zero-shot-classification")
classifier2(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.8445988297462463, 0.11197440326213837, 0.04342682659626007]}

In [ ]:
classifier2(
    "I just cant imagine how you are okay now that i am gone",
    candidate_labels=["music", "politics", "religion"],
)

{'sequence': 'I just cant imagine how you are okay now that i am gone',
 'labels': ['music', 'politics', 'religion'],
 'scores': [0.3816693127155304, 0.3683190643787384, 0.2500116527080536]}

In [ ]:
classifier2(
    "I know we are'nt perfect but i've never felt this way for no one",
    candidate_labels=["music", "politics", "love"],
)

{'sequence': "I know we are'nt perfect but i've never felt this way for no one",
 'labels': ['love', 'music', 'politics'],
 'scores': [0.8635240197181702, 0.07700246572494507, 0.059473536908626556]}

In [ ]:
classifier2(
    "I wish nothing but the best for you",
    candidate_labels=["love", "politics", "business"],
)

{'sequence': 'I wish nothing but the best for you',
 'labels': ['love', 'business', 'politics'],
 'scores': [0.8739268183708191, 0.0768895074725151, 0.049183640629053116]}

In [ ]:
generator = pipeline("text-generation")
generator("I'm not gonna try till you decide'")

No model was supplied, defaulted to gpt2 and revision 6c0e608 (https://huggingface.co/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:1201: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:1288: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


[{'generated_text': 'I\'m not gonna try till you decide\' and then tell me."\n\n"That\'s not your job as it was before you came here, that\'s what you do. Tell him about all the problems and the people who didn\'t take your'}]

In [ ]:
generator = pipeline("text-generation")
generator("I am standing here naked")

No model was supplied, defaulted to gpt2 and revision 6c0e608 (https://huggingface.co/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'I am standing here naked in the dark and I can be totally naked when I want. I am not saying that I have seen much nakedness, but I do know that is what they call nakedness, nakedness of body. So I can'}]

In [ ]:
generator("I want to know", num_return_sequences = 4, max_length = 30,)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'I want to know what you think about the comments on this video. Please send me an email. I would love it!\n\n[youtube_'},
 {'generated_text': 'I want to know what happened before the meeting."\n\nWhen asked a number of previous times about the meeting with Pence, a source close to Spicer'},
 {'generated_text': 'I want to know everything before I get to it and maybe you could tell me how soon I get back to you as we go on this journey"'},
 {'generated_text': "I want to know the people who are in your life, are you a mom who was divorced and you're a father living in this country who is"}]

In [ ]:
unmasker = pipeline("fill-mask")
unmasker("Will you let me be your man so i can <mask> you.", top_k=2)

No model was supplied, defaulted to distilroberta-base and revision ec58a5b (https://huggingface.co/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'score': 0.17046062648296356,
  'token': 12908,
  'token_str': ' marry',
  'sequence': 'Will you let me be your man so i can marry you.'},
 {'score': 0.06134248152375221,
  'token': 2416,
  'token_str': ' trust',
  'sequence': 'Will you let me be your man so i can trust you.'}]

In [ ]:
unmasker("I'm gonna pick up the peices and build up the <mask> house.", top_k=2)

[{'score': 0.10472293943166733,
  'token': 1086,
  'token_str': ' whole',
  'sequence': "I'm gonna pick up the peices and build up the whole house."},
 {'score': 0.08905453234910965,
  'token': 3907,
  'token_str': ' tree',
  'sequence': "I'm gonna pick up the peices and build up the tree house."}]

In [ ]:
ner = pipeline("ner", grouped_entities=True)
ner("My name is Eddy and I work at NodeX iHub as a Machine Learning Engineer here in Nigeria.")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


/usr/local/lib/python3.9/dist-packages/transformers/pipelines/token_classification.py:157: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="simple"` instead.
  warnings.warn(


[{'entity_group': 'PER',
  'score': 0.99871314,
  'word': 'Eddy',
  'start': 11,
  'end': 15},
 {'entity_group': 'ORG',
  'score': 0.9083786,
  'word': 'NodeX iHub',
  'start': 30,
  'end': 40},
 {'entity_group': 'MISC',
  'score': 0.53762555,
  'word': 'Engineer',
  'start': 63,
  'end': 71},
 {'entity_group': 'LOC',
  'score': 0.9997888,
  'word': 'Nigeria',
  'start': 80,
  'end': 87}]

In [ ]:
question_answerer = pipeline("question-answering")
question_answerer(
    question="What work do i do?",
    context="My name is Eddy and I work at NodeX iHub as a Machine Learning Engineer here in Nigeria",
)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.8854089379310608,
 'start': 46,
 'end': 71,
 'answer': 'Machine Learning Engineer'}

In [ ]:
summarizer = pipeline("summarization")
summarizer("""
Neural network models can take up a lot of space on disk, with the original AlexNet being over 200 MB in
float format, for example. Almost all of that size is taken up with the weights since there are often many millions of
these in a single model. Because they’re all slightly different floating-point numbers, simple compression formats like
don’t compress them well. They are arranged in large layers though, and within each layer, the weights tend to be normally
distributed within a certain range, for example, -3.0 to 6.0.
The simplest motivation for quantization is to shrink file sizes by storing the min and max for each layer and then compressing
each float value to an eight-bit integer representing the closest real number in a linear set of 256 within the range.
For example with the -3.0 to 6.0 range, a 0 byte would represent -3.0, a 255 would stand for 6.0, and 128 would represent
about 1.5. This means you can get the benefit of a file on disk that’s shrunk by 75%, and then convert back to float after
loading so that your existing floating-point code can work without any changes.
Another reason to quantize is to reduce the computational resources you need to do the inference calculations, by running
them entirely with eight-bit inputs and outputs. This is a lot more difficult since it requires changes everywhere you do
calculations, but offers a lot of potential rewards. Fetching eight-bit values only require 25% of the memory bandwidth of
floats, so you’ll make much better use of caches and avoid bottlenecking on RAM access. You can also typically use
hardware-accelerated Single-Instruction Multiple Data (SIMD) operations that do many more operations per clock cycle.
In some cases, you’ll have a digital signal processor (DSP) chip available that can accelerate eight-bit calculations
too, which can offer a lot of advantages. (Don’t worry if you don’t fully understand these hardware capabilities,
we will discuss them more in Course 3.)
Moving calculations over to eight-bit will help you run your models faster, and use less power, which is
especially important on mobile devices. It also opens the door to a lot of embedded systems that can’t run
floating-point code efficiently, so it can enable a lot of applications in the TinyML world.
"""
)

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'summary_text': ' Neural network models can take up a lot of space on disk, with the original AlexNet being over 200 MB . Almost all of that size is taken up with the weights since there are often many millions of these in a single model . The simplest motivation for quantization is to shrink file sizes by storing the min and max for each layer and then compressing each float value to an eight-bit integer .'}]

TRANSFORMER PIPELINE (Behind the Pipeline)

In [ ]:
#PROCESSING THE INPUT FOR THE MODEL WITH TOKENIZER

from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
raw_inputs = [
    "All my life i needed someone like you.",
    "What a cruel world",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[  101,  2035,  2026,  2166,  1045,  2734,  2619,  2066,  2017,
         1012,   102],
       [  101,  2054,  1037, 10311,  2088,   102,     0,     0,     0,
            0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], dtype=int32)>}


In [ ]:
#PASSING THE INPUT TO THE TRANSFORMER MODEL

from transformers import TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_97']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(inputs)
print(outputs, " \n")
print(outputs.logits.shape, " \n")
print(outputs.logits)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.6766875,  2.7219949],
       [ 3.2332206, -2.7829645]], dtype=float32)>, hidden_states=None, attentions=None)  

(2, 2)  

tf.Tensor(
[[-2.6766875  2.7219949]
 [ 3.2332206 -2.7829645]], shape=(2, 2), dtype=float32)


In [ ]:
#PROCESSING THE MODEL OUTPUT

import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor(
[[0.00450217 0.9954978 ]
 [0.99756706 0.00243302]], shape=(2, 2), dtype=float32)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1 = "I've been waiting for a HuggingFace course my whole life."
sequence2 = "I hate this so much."

tokens1 = tokenizer.tokenize(sequence1)
ids1 = tokenizer.convert_tokens_to_ids(tokens1)

tokens2 = tokenizer.tokenize(sequence2)
ids2 = tokenizer.convert_tokens_to_ids(tokens2)

input_ids1 = tf.constant([ids1])
input_ids2 = tf.constant([ids2])

print("Input IDs1:", input_ids1)
print("Input IDs2:", input_ids2)


All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


Input IDs1: tf.Tensor(
[[ 1045  1005  2310  2042  3403  2005  1037 17662 12172  2607  2026  2878
   2166  1012]], shape=(1, 14), dtype=int32)
Input IDs2: tf.Tensor([[1045 5223 2023 2061 2172 1012]], shape=(1, 6), dtype=int32)


In [ ]:
print(ids1)

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
